language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-source --dev
  - composer dump-autoload -o
script:
  - phpunit --bootstrap phpunit.php --configuration phpunit.xml FileQueueTest tests\FileQueueTest.php